#include "arduino_secrets.h"
const int leftEncoderPin = 15;
const int rightEncoderPin = 13;
volatile unsigned int leftEncoderCount = 0;
volatile unsigned int rightEncoderCount = 0;
unsigned long lastTime = 0;
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/b6e22bd4-c9f7-4340-bc88-96bdc7e7abe3

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int sa;
  int smtl;
  int smtr;
  int speed;
  bool sw;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
//***************************************************
void countLeftEncoderPulse() {
  leftEncoderCount++;
}

void countRightEncoderPulse() {
  rightEncoderCount++;
}

void setup() {
  pinMode(leftEncoderPin, INPUT_PULLUP);
  pinMode(rightEncoderPin, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(leftEncoderPin), countLeftEncoderPulse, FALLING);
  attachInterrupt(digitalPinToInterrupt(rightEncoderPin), countRightEncoderPulse, FALLING);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(16, OUTPUT);//ena
  pinMode(5, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(0, OUTPUT);
  pinMode(2, OUTPUT);
  pinMode(14, OUTPUT); //ena
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  unsigned long currentTime = millis();
  if (currentTime - lastTime >= 1000) {
    noInterrupts();
    smtl = (2 * PI * leftEncoderCount) / (20);
    smtr = (2 * PI * rightEncoderCount) / (20);
    leftEncoderCount = 0;
    rightEncoderCount = 0;
    interrupts();
    lastTime = currentTime;
  }
  //*******************************************************************
  int m;
  int n;
  if (sw == true) {

    int l = abs(speed*(1 - tan(sa * 3.14 / 180)));
    int r = abs(speed*(1 + tan(sa * 3.14 / 180)));
    
    if(l==0){m=0;}
      else if(l>=1 && l<10){m=100;}
      else if(l>=10 && l<20){m=130;}
      else if(l>=20 && l<30){m=160;}
      else if(l>=30 && l<40){m=190;}
      else if(l>=40 && l<50){m=220;}
      else if(l>=50 && l<60){m=250;}
      else if(l>=60 && l<70){m=280;}
      else if(l>=70 && l<80){m=310;}
      else if(l>=80 && l<90){m=440;}
      else if(l>=90 && l<100){m=470;}
      else if(l>=100 && l<110){m=500;}
      else if(l>=110 && l<120){m=630;}
      else if(l>=120 && l<130){m=660;}
      else if(l>=130 && l<140){m=690;}
      else if(l>=140 && l<150){m=720;}
      else if(l>=150 && l<160){m=750;}
      //else {m=1024;}

      if(r==0){n=0;}
      else if(r>=1 && r<10){n=100;}
      else if(r>=10 && r<20){n=130;}
      else if(r>=20 && r<30){n=160;}
      else if(r>=30 && r<40){n=190;}
      else if(r>=40 && r<50){n=220;}
      else if(r>=50 && r<60){n=250;}
      else if(r>=60 && r<70){n=280;}
      else if(r>=70 && r<80){n=310;}
      else if(r>=80 && r<90){n=440;}
      else if(r>=90 && r<100){n=470;}
      else if(r>=100 && r<110){n=500;}
      else if(r>=110 && r<120){n=630;}
      else if(r>=120 && r<130){n=660;}
      else if(r>=130 && r<140){n=690;}
      else if(r>=140 && r<150){n=720;}
      else if(r>=150 && r<160){n=750;}
      //else {n=1024;}

    digitalWrite(5, HIGH);
    digitalWrite(4, LOW);
    analogWrite(16, m);

    digitalWrite(0, HIGH);
    digitalWrite(2, LOW);
    analogWrite(14, n);
  }

  else {
    digitalWrite(4, LOW);
    digitalWrite(5, LOW);
    analogWrite(16, LOW);
    digitalWrite(0, LOW);
    digitalWrite(2, LOW);
    analogWrite(14, LOW);
  }

}


/*
  Since Speed is READ_WRITE variable, onSpeedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSpeedChange()  {
  // Add your code here to act upon Speed change
}


/*
  Since Sw is READ_WRITE variable, onSwChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwChange()  {
  // Add your code here to act upon Sw change
}


/*
  Since Sm is READ_WRITE variable, onSmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSmChange()  {
  // Add your code here to act upon Sm change
}


/*
  Since Sa is READ_WRITE variable, onSaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSaChange()  {
  // Add your code here to act upon Sa change
}



/*
  Since Smtr is READ_WRITE variable, onSmtrChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSmtrChange()  {
  // Add your code here to act upon Smtr change
}

/*
  Since Smtl is READ_WRITE variable, onSmtlChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSmtlChange()  {
  // Add your code here to act upon Smtl change
}