// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "cac718f7-daba-4206-9e6c-97ade182b1f1";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSaChange();
void onSmtlChange();
void onSmtrChange();
void onSpeedChange();
void onSwChange();

int sa;
int smtl;
int smtr;
int speed;
bool sw;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(sa, READWRITE, ON_CHANGE, onSaChange);
  ArduinoCloud.addProperty(smtl, READWRITE, ON_CHANGE, onSmtlChange);
  ArduinoCloud.addProperty(smtr, READWRITE, ON_CHANGE, onSmtrChange);
  ArduinoCloud.addProperty(speed, READWRITE, ON_CHANGE, onSpeedChange);
  ArduinoCloud.addProperty(sw, READWRITE, ON_CHANGE, onSwChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
